BLACK    = (   0,   0,   0)
WHITE    = ( 255, 255, 255)
GREEN    = (   0, 255,   0)
RED      = ( 255,   0,   0)
BLUE     = (   0,   0, 255)
YELLOW   = ( 255, 255,   0)
TRANS    = (   1,   2,   3)

WIDTH = 800
HEIGHT = 800
FRAME_RATE = 60
PLAYER_COLOR = GREEN
FINISH_COLOR = RED
HALLWAY_COLOR = BLUE
WALL_COLOR = BLACK
WELCOME_MESSAGE = 'Welcome to the Maze! Press ENTER to play.'
FINISH_MESSAGE = 'You made it to the end! Press ENTER to play again'
TEXT_COLOR = WHITE
TEXT_FONT = 'Calibri'
TEXT_SIZE = 30
WALL_CHAR = 'x'
HALLWAY_CHAR = ' '
GAME_TITLE = 'Maze!'
PLAYER_CHAR = '@'
FINISH_CHAR = '$'